### ISSUE TITLE
Possible bug in Zilien reader when EC is supposed to be in the dataset but no EC measurement was ever run

### ISSUE THREAD

**Issue by KennethNielsen** [ixdat/ixdat#114]
[This is a possible bug, as the bug may also be in the software components that produces the data; an internal software component called olefn. I will raise the issue in both projects and cross-reference from olefn and to here, so I can keep track of the fix]

I have attached an example data file and minimal script that reproduces the problem. It produces the following traceback

```python
Traceback (most recent call last):
  File "/home/kenneth/venv/datatreatment/example.py", line 4, in <module>
    ecms_data=ixdat.Measurement.read("2023-04-26 13_48_04 leak rate test.tsv", reader="zilien")
  File "/home/kenneth/venv/datatreatment/.venv/datatreatment/lib/python3.10/site-packages/ixdat/measurements.py", line 227, in read
    obj = reader.read(path_to_file, cls=cls, **kwargs)
  File "/home/kenneth/venv/datatreatment/.venv/datatreatment/lib/python3.10/site-packages/ixdat/readers/zilien.py", line 197, in read
    series, aliases = self._form_series()
  File "/home/kenneth/venv/datatreatment/.venv/datatreatment/lib/python3.10/site-packages/ixdat/readers/zilien.py", line 274, in _form_series
    column_series, aliases_part = self._zilien_dataset_part(
  File "/home/kenneth/venv/datatreatment/.venv/datatreatment/lib/python3.10/site-packages/ixdat/readers/zilien.py", line 299, in _zilien_dataset_part
    count = self._metadata[f"{series_header}_{series_header}_count"]
KeyError: 'pot_pot_count'
```

and the issue is that it is missing the "pot_count" metadata (not "pot_pot_count" as the traceback says). The most likely is that the issue is the olefn, so it should not be adressed in ixdat before investigated in olefn.

[bug.zip](https://github.com/ixdat/ixdat/files/11353397/bug.zip)

**Comment by matenestor** [comment]
It is an internal Zilien bug. If you encounter this problem, use `technique="MS"` when you read the dataset.
