### ISSUE TITLE
Export of `ECOpticalMeasurement` broken.

### ISSUE THREAD

**Issue by ScottSoren** [ixdat/ixdat#124]
It's this script which no longer runs for me:

https://github.com/ixdat/ixdat/blob/main/development_scripts/reader_demonstrators/demo_msrh_sec_reader.py

... and likewise in the spectroelectrochemistry ipynb tutorial.

I think it has to do with upgrading to the new version of pandas, but not sure. Here's the error message:

Traceback (most recent call last):
  File "C:\Users\scott\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-cd444d3be004>", line 1, in <module>
    runfile('C:\\Users\\scott\\git\\ixdat\\development_scripts\\reader_demonstrators\\demo_msrh_sec_reader.py', wdir='C:\\Users\\scott\\git\\ixdat\\development_scripts')
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.2.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\scott\git\ixdat\development_scripts\reader_demonstrators\demo_msrh_sec_reader.py", line 36, in <module>
    sec_meas.export(export_name)
  File "C:\Users\scott\git\ixdat\src\ixdat\exporters\csv_exporter.py", line 67, in export
    self.prepare_header_and_data(measurement, columns, tspan, time_step)
  File "C:\Users\scott\git\ixdat\src\ixdat\exporters\sec_exporter.py", line 61, in prepare_header_and_data
    self.spectra_exporter.export(measurement.spectrum_series, path_to_spectra_file)
  File "C:\Users\scott\git\ixdat\src\ixdat\exporters\spectrum_exporter.py", line 137, in export
    df.to_csv(f, index=False, sep=self.delim, line_terminator="\n")
TypeError: to_csv() got an unexpected keyword argument 'line_terminator'

**Comment by ScottSoren** [comment]
fixed.
